name: RiceHeat
channels:
  - defaults
  - conda-forge
dependencies:
  - cartopy
  - geopandas
  - pandas
  - pip
  - xarray>=0.16.1
  - hdf5
  - libnetcdf
  - dask
  - pip:    
    - descartes
    - esgf-pyclient
    - fiona
    - jupyter
    - jupytext
    - matplotlib
    - myproxyclient
    - nbconvert
    - nc-time-axis
    - numba
    - psychrolib>=2.5.0
    - pydap
