channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.18.0
  - dask=2.29.0
  - geopandas=0.8.1
  - hdf5
  - libnetcdf
  - numba=0.50.1
  - pandas=1.1.2
  - pip
  - scipy=1.5.2
  - xarray=0.16.1
  - pip:    
    - descartes
    - esgf-pyclient
    - fiona
    - jupyter
    - jupytext
    - matplotlib
    - myproxyclient
    - nbconvert
    - nc-time-axis
    - psychrolib==2.5.0
    - pydap
