name: RiceHeat
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - xarray
  - geopandas
  - scipy
  - cartopy
  - numpy
  - netcdf4
  - cftime
  - nc-time-axis
  - psychrolib
  - matplotlib
  - dask
  - distributed
  - jupyter
  - notebook
  - descartes
  - numba
  - pandas
  - python=3.8.2
  - pip
  - pip:
    - netcdf4==1.5.4
    - src==0.0.1
variables:
  STORAGE: data/
